services:
  wiki:
    command: bash -c "bundle install --gemfile /root/docs/Gemfile && bundle exec --gemfile /root/docs/Gemfile jekyll serve --source /root/docs --host 0.0.0.0"
    # command: tail -f /dev/null
    image: jekyll/jekyll
    ports:
      - 4000:4000
    tty: true
    networks:
      - wiki-dev
    volumes:
      - ../docs:/root/docs

networks:
  wiki-dev: